export const USERS = [
  {
    id: 1,
    name: 'Admin User',
    email: 'admin@task.com',
    role: 'admin',
    status: 'Active',
  },
  {
    id: 2,
    name: 'John Developer',
    email: 'developer@task.com',
    role: 'developer',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Sarah Trainee',
    email: 'trainee@task.com',
    role: 'trainee',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Alice Developer',
    email: 'alice@task.com',
    role: 'developer',
    status: 'Active',
  },
  {
    id: 5,
    name: 'Bob Trainee',
    email: 'bob@task.com',
    role: 'trainee',
    status: 'Active',
    assignedDeveloper: 2,
  },
  {
    id: 6,
    name: 'Carol Trainee',
    email: 'carol@task.com',
    role: 'trainee',
    status: 'Active',
    assignedDeveloper: 4,
  },
]

export const PROJECTS = [
  {
    id: 1,
    name: 'E-commerce Platform',
    description: 'Build a full-stack e-commerce application',
    developers: [2, 4],
    status: 'In Progress',
    startDate: '2026-01-15',
    deadline: '2026-06-30',
    progress: 65,
  },
  {
    id: 2,
    name: 'Mobile App',
    description: 'React Native mobile application',
    developers: [2],
    status: 'In Progress',
    startDate: '2026-02-01',
    deadline: '2026-07-31',
    progress: 45,
  },
  {
    id: 3,
    name: 'Dashboard System',
    description: 'Analytics dashboard for business metrics',
    developers: [4],
    status: 'In Progress',
    startDate: '2026-01-20',
    deadline: '2026-05-30',
    progress: 80,
  },
  {
    id: 4,
    name: 'API Documentation',
    description: 'Comprehensive API documentation portal',
    developers: [2],
    status: 'Not Started',
    startDate: '2026-04-01',
    deadline: '2026-05-30',
    progress: 0,
  },
]

export const TASKS = [
  {
    id: 1,
    title: 'Setup project structure',
    description: 'Initialize project with necessary folders and files',
    project: 1,
    assignee: 2,
    priority: 'High',
    status: 'Completed',
    dueDate: '2026-02-01',
  },
  {
    id: 2,
    title: 'Design database schema',
    description: 'Create ER diagrams and database structure',
    project: 1,
    assignee: 4,
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-03-15',
  },
  {
    id: 3,
    title: 'Build user authentication',
    description: 'Implement login and registration system',
    project: 1,
    assignee: 2,
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-03-30',
  },
  {
    id: 4,
    title: 'Create product catalog',
    description: 'Build product listing and detail pages',
    project: 1,
    assignee: 2,
    priority: 'Medium',
    status: 'Pending',
    dueDate: '2026-04-15',
  },
  {
    id: 5,
    title: 'Learn HTML basics',
    description: 'Complete HTML fundamentals course',
    project: null,
    assignee: 3,
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-03-15',
    category: 'HTML',
  },
  {
    id: 6,
    title: 'Learn CSS styling',
    description: 'Master CSS layouts and responsive design',
    project: null,
    assignee: 5,
    priority: 'High',
    status: 'Completed',
    dueDate: '2026-02-28',
    category: 'CSS',
  },
  {
    id: 7,
    title: 'Learn JavaScript fundamentals',
    description: 'Complete JavaScript basics and advanced concepts',
    project: null,
    assignee: 6,
    priority: 'High',
    status: 'In Progress',
    dueDate: '2026-04-15',
    category: 'JavaScript',
  },
]

export const TEAM_STATS = [
  {
    id: 1,
    developerId: 2,
    name: 'John Developer',
    totalProjects: 3,
    totalTasks: 5,
    completedTasks: 1,
    pendingTasks: 4,
    completionRate: 20,
  },
  {
    id: 2,
    developerId: 4,
    name: 'Alice Developer',
    totalProjects: 2,
    totalTasks: 3,
    completedTasks: 2,
    pendingTasks: 1,
    completionRate: 67,
  },
]

export const TRAINEE_PROGRESS = [
  {
    id: 1,
    traineeId: 3,
    name: 'Sarah Trainee',
    assignedTasks: 3,
    completedTasks: 1,
    completionRate: 33,
    htmlProgress: 50,
    cssProgress: 60,
    jsProgress: 40,
    reactProgress: 20,
  },
  {
    id: 2,
    traineeId: 5,
    name: 'Bob Trainee',
    assignedTasks: 2,
    completedTasks: 1,
    completionRate: 50,
    htmlProgress: 100,
    cssProgress: 80,
    jsProgress: 20,
    reactProgress: 0,
  },
  {
    id: 3,
    traineeId: 6,
    name: 'Carol Trainee',
    assignedTasks: 2,
    completedTasks: 2,
    completionRate: 100,
    htmlProgress: 60,
    cssProgress: 50,
    jsProgress: 35,
    reactProgress: 10,
  },
]

export const ACTIVITY_LOG = [
  {
    id: 1,
    user: 'John Developer',
    action: 'completed',
    item: 'Setup project structure',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: 2,
    user: 'Alice Developer',
    action: 'started',
    item: 'Design database schema',
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
  },
  {
    id: 3,
    user: 'Sarah Trainee',
    action: 'completed',
    item: 'Learn HTML basics',
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: 4,
    user: 'Bob Trainee',
    action: 'started',
    item: 'Learn JavaScript fundamentals',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
]
